#!/bin/sh

set -e -u

run_test()
(
	cd "$1"
	"$ESEQ" < input > output
	diff -u expected output
)

########################################

: ${ESEQ=cat}
: ${ESEQ_TESTS=basic-text}

nt=0
np=0
nf=0
for t in $ESEQ_TESTS
do
	echo $t
	if run_test $t
        then
		np=$((np+1))
	else
		nf=$((np+1))
		echo
		echo FAILED: $t
		echo
	fi
done

set +e
echo
echo "Ran $nt total tests"
if [ $nf -eq 0 ]
then
	tput setaf 2 2>/dev/null
	tput bold 2>/dev/null
	echo PASSED
	tput sgr0 2>/dev/null
else
	tput setaf 1 2>/dev/null
	tput bold 2>/dev/null
	echo FAILED
	tput sgr0 2>/dev/null
fi
echo "Passed: $np"
echo "Failed: $nf"

# vim:sw=8 sts=8 ts=8 noet
