#!/bin/sh

set -e

run_test()
(
        echo "Running test $1:"
        echo
	cd "$1"
	"$ESEQ" < input > output
	diff -u expected output
)

########################################

if [ -z "$ESEQ" ]
then
	# ESEQ=../build/eseq
	ESEQ=cat
fi

if [ -z "$ESEQ_TESTS" ]
then
	ESEQ_TESTS=basic-text
fi

nt=0
for t in $ESEQ_TESTS
do
	run_test $t
	nt=$((nt+1))
done

echo SUCCESS
echo $nt tests passed.

# vim sw=8 sts=8 ts=8 noet
