/* c1.h */

const char *c1_labels[][2] = {
	{ NULL, NULL },
	{ NULL, NULL },
	{ "BPH", "BREAK PERMITTED HERE" },
	{ "NBH", "NO BREAK HERE" },
	{ NULL, NULL },
	{ "NEL", "NEXT LINE" },
	{ "SSA", "START OF SELECTED AREA" },
	{ "ESA", "END OF SELECTED AREA" },
	{ "HTS", "CHARACTER TABULATION SET" },
	{ "HTJ", "CHARACTER TABULATION WITH JUSTIFICATION" },
	{ "VTS", "LINE TABULATION SET" },
	{ "PLD", "PARTIAL LINE FORWARD" },
	{ "PLU", "PARTIAL LINE BACKWARD" },
	{ "RI", "REVERSE LINE FEED" },
	{ "SS2", "SINGLE-SHIFT TWO" },
	{ "SS3", "SINGLE-SHIFT THREE" },
	{ "DCS", "DEVICE CONTROL STRING" },
	{ "PU1", "PRIVATE USE ONE" },
	{ "PU2", "PRIVATE USE TWO" },
	{ "STS", "SET TRANSMIT STATE" },
	{ "CCH", "CANCEL CHARACTER" },
	{ "MW", "MESSAGE WAITING" },
	{ "SPA", "START OF GUARDED AREA" },
	{ "EPA", "END OF GUARDED AREA" },
	{ "SOS", "START OF STRING" },
	{ NULL, NULL },
	{ "SCI", "SINGLE CHARACTER INTRODUCER" },
	{ "CSI", "CONTROL SEQUENCE INTRODUCER" },
	{ "ST", "STRING TERMINATOR" },
	{ "OSC", "OPERATING SYSTEM COMMAND" },
	{ "PM", "PRIVACY MESSAGE" },
	{ "APC", "APPLICATION PROGRAM COMMAND" }
};

/* vim:set sw=8 ts=8 sts=8 noet: */
